site_name: nikochiko's solutions to CS:APP

markdown_extensions:
- pymdownx.arithmatex:
    generic: true

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/default.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js

theme:
  name: material
