name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Hamr
        run: |
          curl -f -X POST http://hamr.kaustubh-dev.pipal.in/apps/csapp/deploy
